### ISSUE TITLE
Small Request

### ISSUE THREAD

**Issue by mikhoul** [vanowm/FirefoxCookiesManagerPlus#121]
Hi Thanks for this useful Cookies Manager ! :+1: 

I'm not really familiar with Cookies I just know the basic and one thing I'd like to see quickly in the interface beside the _"New Cookie" - "Edit" and "Delete buttons"_ would be a **Protect/Unprotect** Cookie button. :cookie: 

Also something to see quickly the **HTML5 Cookies** and differentiate them from the standard cookies would be really useful too. Maybe just another "**column**" to filter them like here: http://i.imgur.com/NwKU5xS.png Cause I don't see anything about HTML5 cookie and on **AMO** it's say that FCMP support it.

Since I begun to learning JS to do more Userscript I will have to learn more about cookies and headers and you're addon will be very useful. :smiley_cat: 

Best Regards ! :octocat:

**Comment by vanowm** [comment]
The protect/unprotect button(s) available when you enabled View ->Protected

![cmp_protect](https://cloud.githubusercontent.com/assets/511517/19094481/4d9be5ec-8a5e-11e6-99fb-6b96e82fe730.png)

HTML5 cookies support was once added in [v1.7](https://addons.mozilla.org/en-US/firefox/addon/cookies-manager-plus/versions/1.7) and it failed miserably because it made the whole browser freeze on "slow" computers...It would require totally rewrite the addon to be able add HTML5 support. It's planned, but won't happened until v2. (and thanks for pointing out at AMO's description, forgot to update it.

**Comment by mikhoul** [comment]
Thanks @vanowm for the quick reply, but sadly the protected is not available on my setup.  🙀

![Screenshot](http://i.imgur.com/7eLmpl4.png)

Just to be sure here's the spec:   Win7/64 + Firefox 49.0.1 :computer: 

My guess is that your XPI version is not exactly the same as mine.

In meantime for the HTML cookies :cookie: do you know of a another software to manage them ? 

Suggestion for the HTML5 maybe you could just add the feature as "EXPERIMENTAL" and "OPT-IN" so we have to check a box on the interface to enable it. Just write "_**Experimental feature at your own risk**_" beside the checkbox.  

Of better release it in the **Beta Channel** on **AMO** till it's ready. I see more and more website that use regular cookies and HTML5 Cookies side by side, it's hard to manage.  :octocat: 

Best Regards :smiley:

**Comment by mikhoul** [comment]
@vanowm Do you have a solution for the "protected button" ?

**Comment by vanowm** [comment]
The protected button only shows when [CookieKeeper](https://addons.mozilla.org/en-US/firefox/addon/cookiekeeper/) is installed and enabled.

As of HTML5 cookies, sorry, I don't know any other software, other then editing webappsstore.sqlite directly with something like SQLite Expert
Adding "experimental" support for HTML5 is also out of questions with current code.
