### ISSUE TITLE
How Do I Use Cookie Manager?

### ISSUE THREAD

**Issue by koolx** [vanowm/FirefoxCookiesManagerPlus#130]
I got 3 questions:

1) How do I use CM? I want to only protect cookies of websites I log into, like gmail. But when I protect all cookies related to gmail and then delete all non-protected cookies, I end up typing in my username and password again, as if the cookies weren't protected in the first place.

2) How do I ensure all non-protected cookies get deleted automatically when I close Firefox?

3) It says protecting session cookies won't do anything. I don't understand. Can someone explain?

**Comment by vanowm** [comment]
Cookie protection is done by [CookieKeeper](https://addons.mozilla.org/firefox/addon/cookiekeeper) addon. If it works when you use CookieKeeper's own interface, but doesn't work with CM+, then it could be issue with CM+ integration with CookieKeeper (feel free start a new issue if that's the case)
Otherwise you might want contact CookieKeeper support regarding protecting cookies and how to use it.

I really can't answer any of these question, because I don't use CookieKeeper myself and know very little how it works.
Sorry.

**Comment by koolx** [comment]
Hey,
    
    I created this thread in the wrong forum. I thought you were the
    creeator of cookiekeeper..
