### ISSUE TITLE
2 Issues

### ISSUE THREAD

**Issue by lino10** [vanowm/FirefoxCookiesManagerPlus#73]
I see that the slow searches and hangs already fixed in 1.8. But I still have 2 issues
1. If I open the 'options' in addons manager, it opens not only the option window but also the cookie manager window
2. The cookies manager menu becomes submenu and I can click the parent, if you want to implement submenu please make the parent unclickable. Also please add 'options' in the submenu.

Thank you :)

**Comment by vanowm** [comment]
1. it was done by design, because addon manager opens options as modal window which means browser become unusable while options window is opened. Opening CM+ window together with options solved that problem.
   It will be changed in v1.9 though
2. the submenu sets filter with current website, while clicking on button itself opens CM+ with previously used filter (nobody likes submenus, so making CM+ open via submenu only is a bad idea)

P.S.
next time please separate issues, thanks.
