### ISSUE TITLE
CM+ asks for master password during FF startup?

### ISSUE THREAD

**Issue by myron0815** [vanowm/FirefoxCookiesManagerPlus#88]
I've set a master password inside FF.

Since a few days, i get the "please enter master password" box, when starting FF!
Didn't happen before.
Disabling CM+ immediately resolves this issue on FF restart...

**Comment by vanowm** [comment]
Disable **extensions.cookiesmanagerplus.readonlyencrypt** in about:config and then set any cookie data to read-only, wait 30 seconds to allow CM+ save it to file or close CM+ window, after that you can remove read-only from that cookie.

Note, that disabling encryption will save read-only data as plain text onto hard drive. It probably not a big deal, because cookies themselves are not encrypted and can be read by anyone with access to the computer anyway.

**Comment by myron0815** [comment]
thx.
this does the trick...

**Comment by Przbl** [comment]
Forgive me, but I don't get it. So I set _extensions.cookiesmanagerplus.readonlyencrypt_ to false. The master password prompt is still coming up. 
Is setting some cookie to read-only and reverting that after 30 sec really necessary? Did that (in Cookie Culler since I have no idea how to do that in Cookie Manger), but nothing happened and I still have that master password prompt.

**Comment by vanowm** [comment]
Yes, it's necessarily in current version, because it needs to overwrite encrypted data with non-encrypted. Currently it doesn't save anything to hard drive unless something was changed (added/removed).
Read-only feature is in CM+itself, not Cookie Culler related.

There is a "R" or "R/W" buttons on left side of Content, Send For, Expires and Http Only info rows, they are represent the read-only state of data in the cookie. "R" = Read-only, "R/W" = Read/Write (normal state)

![](http://i.imgur.com/O7nZzRy.png?1)

Click on any of these buttons and wait 30 seconds
v1.3 will have easy accessed option for this and won't need to do anything manually or wait 30 seconds.

**Comment by Przbl** [comment]
Ahh, I didn't notice that those "R" and "R/W" are buttons. Worked like a charm, thanks!
